### ISSUE TITLE
I want to change where the VHD gets installed by the script.

### ISSUE THREAD

**Issue by XcelOrbit** [jamesstringerparsec/Easy-GPU-P#36] opened 2022-01-10 06:38 UTC
The script doesn't appear to have and option to change where the VHD file gets put in terms of its directory and I have an SSD I want to put the VHD in but by default it installs it in my Public Documents folder. Is there a way to change where it gets installed? And if not, is it possible that this feature will be added in the future?

**Comment by jamesstringerparsec** [comment] 2022-01-10 09:13
Closing, this is a duplicate of https://github.com/jamesstringerparsec/Easy-GPU-P/issues/29

**Closed by jamesstringerparsec** 2022-01-10 09:13 UTC
